/**
 * QueryResponse.java
 * <p><b>RAG Role:</b> Outbound DTO for RAG query results. Carries the generated answer
 * plus rich metadata about how the pipeline executed — HyDE hypothesis, MMR stats,
 * chunk counts, latency, and optional per-chunk detail for debugging.
 * <p><b>Learning Note:</b> A well-designed RAG response DTO should expose enough
 * pipeline metadata to let you evaluate quality: Was HyDE used? How many chunks were
 * retrieved vs selected? What was the latency? This supports iterative improvement.
 * <p><b>LEARN:</b> App 1 returned only {answer, question, latencyMs}. App 2's richer
 * response enables observability into every stage of the advanced pipeline.
 * @author Sathishkumar Krishnan
 * @version 1.0.0
 */
package com.sathish.rag.advanced.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class QueryResponse {

    /** The LLM-generated answer. */
    private String answer;

    /** The original question echoed back. */
    private String question;

    /** The hypothetical answer generated by HyDE (null if HyDE was disabled). */
    private String hydeHypothesis;

    /** Whether HyDE query expansion was used for this request. */
    private boolean hydeUsed;

    /** Whether MMR re-ranking was applied. */
    private boolean mmrUsed;

    /** The MMR lambda value used (if MMR was applied). */
    private Double mmrLambda;

    /** Number of candidate chunks before MMR re-ranking. */
    private int chunksBeforeReranking;

    /** Number of chunks selected after MMR re-ranking for the LLM context. */
    private int chunksAfterReranking;

    /** End-to-end pipeline latency in milliseconds. */
    private long latencyMs;

    /** UTC timestamp when the response was generated. */
    private Instant timestamp;

    /** Per-chunk details (populated only if request.includeChunks=true). */
    private List<ChunkDetail> retrievedChunks;
}
